# Generated by Django 4.2.11 on 2024-03-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('status', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
