# Generated by Django 4.2.11 on 2024-03-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URL',
            new_name='URLStatus',
        ),
    ]
